import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    Column,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    TIMESTAMP,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from app.database import Base


def _now():
    return datetime.now(timezone.utc)


class User(Base):
    # Schema owned by Clerk — defined here for FK references only.
    # Alembic must NOT include this table in autogenerated migrations.
    __tablename__ = "users"
    __table_args__ = {"extend_existing": True}

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    clerk_user_id = Column(String, unique=True, nullable=False)
    email = Column(String, unique=True, nullable=True)
    # Prisma created this table with camelCase column names
    created_at = Column("createdAt", TIMESTAMP(timezone=True), default=_now)


class ResearchJob(Base):
    __tablename__ = "research_jobs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    query = Column(Text, nullable=False)
    status = Column(
        Enum("pending", "running", "done", "failed", name="job_status"),
        nullable=False,
        default="pending",
    )
    created_at = Column(TIMESTAMP(timezone=True), default=_now)
    completed_at = Column(TIMESTAMP(timezone=True), nullable=True)

    report = relationship("Report", back_populates="job", uselist=False)


class Report(Base):
    __tablename__ = "reports"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    job_id = Column(UUID(as_uuid=True), ForeignKey("research_jobs.id"), nullable=False)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    report_markdown = Column(Text, nullable=True)
    raw_context = Column(JSONB, nullable=True)
    suggested_followups = Column(JSONB, nullable=True)
    sentiment_positive = Column(Float, nullable=True)
    sentiment_neutral = Column(Float, nullable=True)
    sentiment_negative = Column(Float, nullable=True)
    youtube_comment_volume = Column(Integer, nullable=True)
    source_count = Column(Integer, nullable=True)
    overall_sentiment = Column(
        Enum("Positive", "Mixed", "Negative", name="sentiment_label"),
        nullable=True,
    )
    created_at = Column(TIMESTAMP(timezone=True), default=_now)

    job = relationship("ResearchJob", back_populates="report")
    follow_ups = relationship("FollowUp", back_populates="report")


class FollowUp(Base):
    __tablename__ = "follow_ups"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    report_id = Column(UUID(as_uuid=True), ForeignKey("reports.id"), nullable=False)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    question = Column(Text, nullable=False)
    answer = Column(Text, nullable=True)
    turn_number = Column(Integer, nullable=False)
    created_at = Column(TIMESTAMP(timezone=True), default=_now)

    report = relationship("Report", back_populates="follow_ups")
