"""initial schema

Revision ID: b43e9c67fa45
Revises: 
Create Date: 2026-06-03 17:07:06.727059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b43e9c67fa45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='job_status'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_markdown', sa.Text(), nullable=True),
    sa.Column('raw_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_followups', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sentiment_positive', sa.Float(), nullable=True),
    sa.Column('sentiment_neutral', sa.Float(), nullable=True),
    sa.Column('sentiment_negative', sa.Float(), nullable=True),
    sa.Column('reddit_volume', sa.Integer(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('overall_sentiment', sa.Enum('Positive', 'Mixed', 'Negative', name='sentiment_label'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['research_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow_ups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow_ups')
    op.drop_table('reports')
    op.drop_table('research_jobs')
    # ### end Alembic commands ###
