"""switch to clerk auth

Revision ID: 707c4d06cff5
Revises: b43e9c67fa45
Create Date: 2026-06-03 18:30:17.471707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '707c4d06cff5'
down_revision: Union[str, None] = 'b43e9c67fa45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sessions_sessionToken_key', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('verification_tokens_identifier_token_key', table_name='verification_tokens')
    op.drop_index('verification_tokens_token_key', table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_index('accounts_provider_providerAccountId_key', table_name='accounts')
    op.drop_table('accounts')
    # users table — manual: not covered by autogenerate
    op.add_column('users', sa.Column('clerk_user_id', sa.String(), nullable=True))
    op.create_unique_constraint('users_clerk_user_id_key', 'users', ['clerk_user_id'])
    op.drop_column('users', 'name')
    op.drop_column('users', 'image')
    op.drop_column('users', 'emailVerified')
    op.drop_column('users', 'hashedPassword')
    op.alter_column('users', 'clerk_user_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('providerAccountId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session_state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='accounts_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='accounts_pkey')
    )
    op.create_index('accounts_provider_providerAccountId_key', 'accounts', ['provider', 'providerAccountId'], unique=True)
    op.create_table('verification_tokens',
    sa.Column('identifier', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False)
    )
    op.create_index('verification_tokens_token_key', 'verification_tokens', ['token'], unique=True)
    op.create_index('verification_tokens_identifier_token_key', 'verification_tokens', ['identifier', 'token'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sessionToken', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('expires', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='sessions_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey')
    )
    op.create_index('sessions_sessionToken_key', 'sessions', ['sessionToken'], unique=True)
    # users table — manual: reverse clerk migration
    op.drop_constraint('users_clerk_user_id_key', 'users', type_='unique')
    op.drop_column('users', 'clerk_user_id')
    op.add_column('users', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('emailVerified', postgresql.TIMESTAMP(precision=3), nullable=True))
    op.add_column('users', sa.Column('hashedPassword', sa.Text(), nullable=True))
    # ### end Alembic commands ###
